Algoritmo "semnome"

Var
   n1 , n2: inteiro


Inicio
   escreval("Digite o primeiro número:  ")
   leia (n1)
   escreval("Digite o segundo número:  ")
   leia (n2)
   
   se(n1 > n2) entao
     escreval("O primeiro número é maior")
   fimse
   
   se( n1< n2)entao
       escreval("O segundo número é maior")
    fimse
   se (n1= n2)entao
      escreval("Os números são iguais")
    fimse
Fimalgoritmo