Algoritmo "semnome"



Var
 n1: inteiro
 


Inicio
 escreval("Informe um número")
 leia(n1)
 
 
  se(n1<10) entao
           escreval("Número MENOR  que 10")
  senao
           se(n1 >= 10) E (n1 <=50) entao
              escreval("número entre 10 e 50")
       senao
            se(n1 >= 51) e (n1<= 60) entao
              escreval("Número entre 51 e 60")
        senao
            escreval("Número Mior que 60")
     fimse
   fimse
 fimse
 
Fimalgoritmo